In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/processed/food_waste_master_dataset.csv")

df["Date"] = pd.to_datetime(df["Date"])

In [3]:
df["Inventory_Turnover"] = (
    df["Inventory_Sold"] / df["Inventory_Received"]
)

In [4]:
df[["Inventory_Received",
    "Inventory_Sold",
    "Inventory_Turnover"]].head()

   Inventory_Received  Inventory_Sold  Inventory_Turnover
0                 410             229            0.558537
1                 148             142            0.959459
2                 143              74            0.517483
3                 288             266            0.923611
4                 361             353            0.977839

## Observation

Inventory Turnover measures the proportion of inventory sold.

Higher values indicate efficient inventory movement, while lower values may indicate excess stock and a higher risk of food waste.

In [5]:
# Calculate the percentage of inventory wasted

df["Waste_Percentage"] = (
    df["Waste_Quantity"] / df["Inventory_Received"]
) * 100

In [6]:
df[[
    "Inventory_Received",
    "Waste_Quantity",
    "Waste_Percentage"
]].head()

   Inventory_Received  Waste_Quantity  Waste_Percentage
0                 410           18.55          4.524390
1                 148            0.57          0.385135
2                 143            7.76          5.426573
3                 288            2.04          0.708333
4                 361            0.54          0.149584

## Observation

Waste Percentage represents the proportion of received inventory that was wasted.

This feature provides a standardized measure of waste, allowing fair comparison across products with different inventory levels.

### Business Insight

Products with a high waste percentage should be prioritized for inventory optimization, pricing strategies, or promotional campaigns to reduce losses.

Sales Velocity = Inventory Sold / Shelf Life Days

In [7]:
# Calculate the average number of units sold per shelf-life day

df["Sales_Velocity"] = (
    df["Inventory_Sold"] / df["Shelf_Life_Days"]
)

In [8]:
df[[
    "Inventory_Sold",
    "Shelf_Life_Days",
    "Sales_Velocity"
]].head()

   Inventory_Sold  Shelf_Life_Days  Sales_Velocity
0             229                5       45.800000
1             142               10       14.200000
2              74               90        0.822222
3             266                7       38.000000
4             353              120        2.941667

## Observation

Sales Velocity measures how quickly products are sold relative to their shelf life.

Higher values indicate faster product movement, reducing the likelihood of expiry and food waste.

### Business Insight

Products with low sales velocity should be monitored closely. Businesses can improve sales through discounts, promotions, or stock transfers before products expire.

Stock Utilization=Inventory Sold/Inventory Sold+Inventory Remaining

In [9]:
# Calculate stock utilization

df["Stock_Utilization"] = (
    df["Inventory_Sold"] /
    (df["Inventory_Sold"] + df["Inventory_Remaining"])
)

In [10]:
df[[
    "Inventory_Sold",
    "Inventory_Remaining",
    "Stock_Utilization"
]].head()

   Inventory_Sold  Inventory_Remaining  Stock_Utilization
0             229                  181           0.558537
1             142                    6           0.959459
2              74                   69           0.517483
3             266                   22           0.923611
4             353                    8           0.977839

## Observation

Stock Utilization measures how efficiently the available inventory was utilized.

Higher values indicate better inventory management, while lower values suggest excess inventory and potential waste.

### Business Insight

Stores with consistently low stock utilization may require improved demand forecasting or reduced inventory levels to minimize food waste.

In [12]:
# Create expiry risk category

df["Expiry_Risk"] = np.where(
    df["Expiry_Days_Left"] <= 7,
    "High",
    np.where(
        df["Expiry_Days_Left"] <= 30,
        "Medium",
        "Low"
    )
)

In [13]:
df[[
    "Expiry_Days_Left",
    "Expiry_Risk"
]].head(10)

   Expiry_Days_Left Expiry_Risk
0                 3        High
1                 6        High
2                54         Low
3                 4        High
4                72         Low
5                 9      Medium
6                 4        High
7                 7        High
8                 3        High
9                 3        High

## Observation

Products are categorized into High, Medium, and Low expiry risk based on the remaining shelf life.

This feature helps identify products that require immediate attention.

### Business Insight

Products with High Expiry Risk should be prioritized for discounts, promotions, or stock transfers to reduce waste.

In [14]:
# Create high temperature flag

df["High_Temperature_Flag"] = np.where(
    df["Temperature"] > 30,
    1,
    0
)

In [15]:
df[[
    "Temperature",
    "High_Temperature_Flag"
]].head(10)

   Temperature  High_Temperature_Flag
0           30                      0
1           16                      0
2           31                      1
3           29                      0
4           26                      0
5           35                      1
6           39                      1
7           38                      1
8           33                      1
9           27                      0

## Observation

The High Temperature Flag identifies records where the temperature exceeds 30°C.

This feature can help the model learn the impact of high temperatures on food spoilage.

### Business Insight

During periods of high temperature, businesses can strengthen cold-chain monitoring, increase refrigeration checks, and adjust inventory levels for temperature-sensitive products.

In [16]:
# Save the feature-engineered dataset

df.to_csv("../data/processed/food_waste_feature_engineered.csv", index=False)

print("Feature-engineered dataset saved successfully!")

Feature-engineered dataset saved successfully!

In [17]:
df.columns

Index(['Store_ID', 'Product_ID', 'Inventory_Received', 'Inventory_Sold',
       'Inventory_Remaining', 'Product_Name', 'Category', 'Brand',
       'Shelf_Life_Days', 'Unit_Price', 'Unit', 'Storage_Type', 'Store_Name',
       'City', 'State', 'Region', 'Store_Type', 'Store_Size', 'Opening_Year',
       'Demand_Score', 'Demand_Level', 'Month', 'Promotion',
       'Discount_Percentage', 'Date', 'Temperature', 'Humidity', 'Rainfall',
       'Weather', 'Weekend', 'Holiday', 'Expiry_Days_Left', 'Waste_Quantity',
       'Waste_Cost', 'Waste_Risk', 'Inventory_Recommendation',
       'Inventory_Turnover', 'Waste_Percentage', 'Sales_Velocity',
       'Stock_Utilization', 'Expiry_Risk', 'High_Temperature_Flag'],
      dtype='object')